### ISSUE TITLE
I don’t get it

### ISSUE THREAD

**Issue by Frowny** [stanfieldr/ghetto-skype#1]
Ubuntu 16.04
when launching from app menu the launcher icon appears for a few seconds, no window appears.
Starting from terminal

     ~/: npm --prefix /opt/ghetto-skype start

    > ghetto-skype@1.0.0 start /opt/ghetto-skype
    > electron .
No window.

**Comment by stanfieldr** [comment]
If you set StartMinimized to false in settings.json, does it start? I'm actually using 16.04 at work, I'll take a look later today :)

**Comment by Serojin** [comment]
Mint 17.3, same issue (I'm sure not a shock)
Setting StartMinimized seemed to work for me.

**Comment by stanfieldr** [comment]
I updated the settings so the window opens by default.
