### ISSUE TITLE
Multiple Skype instances

### ISSUE THREAD

**Issue by grottas** [stanfieldr/ghetto-skype#101]
Is it possible to allow multiple Skype instances?

There are cases where people can have multiple Skype accounts, at least one personal and one for working.

Is this acceptable? In case it is not, what would be the reasons?

**Comment by stanfieldr** [comment]
You can comment it out this bit in src/main.js

```javascript
if (shouldQuit) {
	app.quit();
	return;
}
```

After that multiple instance will start. It wouldn't be all that complicated to support, I just need to build some sort of tab interface to allow you to be logged into both. Something a little easier to do would be like how chrome handles profiles and you can switch between your accounts. It wouldn't be as nice as being logged in at the same time though.
