### ISSUE TITLE
Elementary OS Loki tray icon

### ISSUE THREAD

**Issue by mikield** [stanfieldr/ghetto-skype#102]
The icon at Elementary OS Loki is not showing up after starting the app.

**Comment by popvladaurel** [comment]
Editing _ghetto-skype.desktop_ in _/usr/share/applications_ to look like this brings it to Wingpanel and sets it visible in Slingshot. 



**[Desktop Entry]**
Name=Ghetto Skype
Encoding=UTF-8
Comment=Web Skype + Tray Icon + Notifications
GenericName=Ghetto Skype
Exec=env XDG_CURRENT_DESKTOP=Unity ghetto-skype %U
Icon=ghetto-skype
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;Messaging;

I also replaced _skype24.png_ in _/usr/share/ghetto-skype/resources/app/assets/tray/_ with the attached white variant for a more harmonious look.

![skype24](https://cloud.githubusercontent.com/assets/23455688/21083496/89209bd6-bffa-11e6-93e0-00db6e79037e.png) <- yes, there is a small white skype logo here :)

**Comment by davidak** [comment]
@popvladaurel could you create a Pull Request?

**Comment by stanfieldr** [comment]
This may be fixed in the new version because I'm using electron-builder to make the deb/rpms now

**Comment by popvladaurel** [comment]
Yes, it is fixed in 1.5.0. Thank you.
