### ISSUE TITLE
No symlink in /usr/bin/ (amd64 deb package)

### ISSUE THREAD

**Issue by pitsi** [stanfieldr/ghetto-skype#114]
There used to be a symlink of "/opt/Ghetto Skype/ghetto-skype" in /usr/bin/ in 1.4.1, so I could start ghetto-skype from the terminal, from a script and from anywhere my $PATH can be used. Now there isn't. Can you please add it back?

I know that the .desktop file points to "/opt/Ghetto Skype/ghetto-skype" so there is no problem with it, I just want the old functionality back.

The above was only checked in the amd64 deb package. I do not use the rest

**Comment by dayfuaim** [comment]
The same I have.

**Comment by stanfieldr** [comment]
I went ahead and fixed this [here](https://github.com/electron-userland/electron-builder/pull/1060), will update when they merge and tag. Temporarily you can `rm /usr/local/bin/ghetto-skype` and `ln -sf '/opt/Ghetto Skype/ghetto-skype' '/usr/local/bin/ghetto-skype'`

**Comment by pitsi** [comment]
Although I can not understand a word from the commit, thank you for the fix :)
Can I close the bug report now or wait until the next release?

**Comment by douglascrp** [comment]
@stanfieldr the symbolic link solution worked for me.
I believe that should be added in a new release.

**Comment by pitsi** [comment]
I am closing this since ghetto-skype is no longer maintained... and because the above commit probably fixed it some time ago and I could not check.
