### ISSUE TITLE
Able to make audio calls, but unable to hang up, nor recieve a call

### ISSUE THREAD

**Issue by miyoyo** [stanfieldr/ghetto-skype#12]
Whenever I make a call, I need to hang up at the other end, because the button doesn't work.

Also, I have the "Please install our shit" whenever I want to answer a recieved call.

But, This is remarkable work and you deserve tons of kudos for that one

**Comment by stanfieldr** [comment]
I will be tracking the M$ plugin in #10; however, I will also take a look at the hang up button.

**Comment by stanfieldr** [comment]
I was able to reproduce the problem with ending the call yesterday, but can't today. Looks like Skype fixed it.
