### ISSUE TITLE
Skype officially released web skype app for Linux

### ISSUE THREAD

**Issue by vasekch** [stanfieldr/ghetto-skype#125]
This issue is more a question weather maintain ghetto-skype when there is an official version out now.

![image](https://user-images.githubusercontent.com/2572537/27327005-157e158c-55a5-11e7-8c00-a53ba568bd58.png)

With announcement of deprecation of old GTK Skype app from 1st July 2017, official web app wrapped for desktop has been released, so called Skype 5.3

![image](https://user-images.githubusercontent.com/2572537/27326979-07cd0b96-55a5-11e7-8bb6-dcab0d1c2ff9.png)

@stanfieldr Thank you for your amazing work!

**Comment by bhelm** [comment]
i dont like the fixed-width chat size, the quoting style and the representation of the web skype. i really like the more productive, xchat-like style of the old skype linux client. i could imagine that ghetto-skype could become a customizable and themeable alternative for the official "skypeforlinux" client.

**Comment by msmoby** [comment]
The official version only supports 32 bit arch

**Comment by bhelm** [comment]
the new "skypeforlinux" supports x64:
```
# file /usr/share/skypeforlinux/skypeforlinux
/usr/share/skypeforlinux/skypeforlinux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=57b6d0700088063f4abc1a19526f85aa8eed600b, stripped```

**Comment by msmoby** [comment]
@Bhelm I'm so sorry..  I *meant * to type The official version only supports **64**
bit arch..((

I have installed ghetto-skype on Linux 32-bit arch and am very happy

**Comment by hako1** [comment]
I am using 17.04 (Unity) 64 bit. Today, I tried skypeforlinux 5.4.0.1 from the official repo (sudo apt install skypeforlinux).
Unfortunately, after a first open, the app stayed in memory with no icon and no way of accessing it (had to kill). The workaround (env XDG_CURRENT_DESKTOP=Unity) also did not bring up an icon.
On another machine 17.04 Gnome runs Skype without problems.
That's how I came to Ghetto-Skype, which installed ok, and runs so far. However, I still have no indicator icon, so that I am afraid to close the app.

**Comment by stanfieldr** [comment]
@hako1 It seems like the electron/builder version used in packaging 1.5 had a bug. In the next release, it'll fix this issue. Here's a deb of the in-progress 1.6 https://stanfield.it/downloads/ghetto-skype_1.6.0_amd64.deb

**Comment by stanfieldr** [comment]
As a programmer, I find proprietary software like a jail cell. If they made it open source, I probably wouldn't be using the Ghetto. As yall may have noticed I haven't been releasing versions lately, but I do use this daily at my work/home and will make updates if it stops working. I am merging pull requests as well, we got a notification count on the tray icon from a contributor, really nice feature. Too bad he couldn't merge it to the official version ;)
