### ISSUE TITLE
Ability to theme Skype using CSS

### ISSUE THREAD

**Issue by stanfieldr** [stanfieldr/ghetto-skype#13]
You should be able to drop a folder containing css into a "themes" directory and change the theme via settings.

**Comment by rohdef** [comment]
I concur, especially, so we could style the smilies. Whatever designer who though "Hey let's make them enormous" should be fired IMO

**Comment by stanfieldr** [comment]
This is now in [v1.3.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.3.0)
