### ISSUE TITLE
ghetto skype failing to even start after upgrading to ubuntu 17.10

### ISSUE THREAD

**Issue by RaulBalboa** [stanfieldr/ghetto-skype#147]
Not sure if this is a known issue. Or just  something on my end. Finally upgraded my old ubuntu 17.04 distro and  now i notice that ghetto skype fails to even launch. I get a loading symbol on my desktop when moving the mouse cursor. But after about 35 seconds it just stops and nothing loads up. Not sure how to even check to see what is causing this. Or if there is any terminal command to see what the problem may be? BTW i'm on a 32 bit machine, so snapd skype isn't even an option.

**Comment by stanfieldr** [comment]
Yea I just tried on Ubuntu 17.10 as well and doesn't seem to be working with the 1.5 package. I can get 1.6 to work if I build the package from source. It doesn't have everything I wanted to put into 1.6, but it's stable, so I am probably going to release it today.

**Comment by RaulBalboa** [comment]
Sounds good stanfieldr! Now i can stop trying to reinstall older versions now that i know it's a problem. I'll keep an eye for 1.5 version when you release it.

**Comment by RaulBalboa** [comment]
Downloading now! I'll report back how it runs. Thanks Stanfieldr.

**Comment by RaulBalboa** [comment]
One thing tho stan. I'm pretty sure i was able to receive video calls with the ghetto skype i had installed? I even remember watching a video on youtube and the guy who made the video also showed video calls worked no problem ? Are they NOT supposed to work?

**Comment by stanfieldr** [comment]
Oh wow that's pretty cool. Video calls weren't working when I originally started developing it, I suspect because of WebRTC support in Chrome lacked. But I've been keeping Ghetto Skype up to date with electron, so support may be improving as we pull in newer versions.
