### ISSUE TITLE
Is "require('remote')" needed?

### ISSUE THREAD

**Issue by techwiz24** [stanfieldr/ghetto-skype#16]
Please forgive my ignorance, but where are you getting the [`remote` module](https://github.com/stanfieldr/ghetto-skype/blob/develop/views/skype.js#L4-L5) from? I don't see it listed as an explicit dependency. 

Its purpose seems to be to be able to load the `tray.js` module from this subdirectory `views/` and still have all the `require()`'s in that file reference the correct module path. I'm trying to package the latest version for the [AUR](https://aur.archlinux.org/packages/ghetto-skype), and would like to keep this package decoupled from electron so we can use a globally installed copy of electron and simply `/usr/bin/electron /opt/ghetto-skype`, which also saves ~40mb per electron app.

Simply adding `remote` as a dependency and `npm install --production` does not seem to work, it looks like that module ships as a coffee script library and may require compilation before use, but I may be missing something. Furthermore, it looks like [that module](https://www.npmjs.com/package/remote) isn't even related to how it is being used in this context...

My initial attempt to fix this was to just require `tray.js` relatively (ex, `require('../tray');` in `views/skype.js`), but then `require('electron')` doesn't resolve anymore, which I think is due to the way `require()` searches for modules in this specific case.

Do you have any suggestions for resolving this for users with external copies of `electron`, or is this going to be an unsupported configuration?

I'm not entirely opposed to using a bundled electron, but if I can save 40mb for every electron app and pay it once, I'd rather be able to do that.

**Comment by stanfieldr** [comment]
Electron runs two processes: 1) the main process 2) the renderer process

The tray, spawning xdg-open, and launching browser windows are done in the main process whereas the browser specific code is run in the renderer process.

remote basically provides a way to communicate from the renderer process to the main process

Maybe `electron.remote.require` will fix this issue too?

**Comment by techwiz24** [comment]
Yes, that seems to have fixed it, thank you very much for the quick feedback and explanation!
