### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by georgenetu** [stanfieldr/ghetto-skype#18]
I accidentally checked the Microsoft Account option in settings and now I can't uncheck it.

![bug](https://cloud.githubusercontent.com/assets/3518650/15321495/755ced8e-1c3f-11e6-9cb1-b0177099bbfd.png)

I've uninstalled it twice, but the settings are still kept somewhere. Any quick workaround to purge everything related to ghetto until a fix is provided?

**Comment by stanfieldr** [comment]
Are you running v1.2.0? This should be fixed in v1.2.1. As a workaround, you can open `~/.config/Ghetto\ Skype/settings.json` in your favorite text editor and change where it says `"MicrosoftAccount": true,` to "MicrosoftAccount": false,

**Comment by georgenetu** [comment]
Thanks, it worked.
