### ISSUE TITLE
Call closes when other caller starts sharing screen

### ISSUE THREAD

**Issue by fnvherk** [stanfieldr/ghetto-skype#19]
As soon as my friend tried sharing screens, the call immediately closed.

**Comment by fnvherk** [comment]
I should also note that my friend was using the windows client.

**Comment by stanfieldr** [comment]
It looks like Web Skype needs some more development in the WebRTC department, so I can only support the audio calls for the time being. I'm looking into making a workaround for this, but I don't want to promise anybody anything I can't deliver.

**Comment by fnvherk** [comment]
Alright. Thank you.
