### ISSUE TITLE
Needs RPM/DEB build process

### ISSUE THREAD

**Issue by stanfieldr** [stanfieldr/ghetto-skype#2]
Rather than using make, it would be nice to be able to install Ghetto Skype with a package manager.

**Comment by jclrb** [comment]
[fpm - effing package management](https://github.com/jordansissel/fpm/wiki), just head about it yesterday, but worth a look?

**Comment by stanfieldr** [comment]
Nice this looks pretty sweet! I'll take a look.

**Comment by stanfieldr** [comment]
Added but somehow seemed more complicated than just doing make install lol... Leaving it out unless someone wants deb/rpm
