### ISSUE TITLE
Blank white window when starting without network connection

### ISSUE THREAD

**Issue by lucidfox** [stanfieldr/ghetto-skype#20]
Under KDE Plasma 5.5 (Ubuntu 16.04), when I add ghetto-skype to autostart using the application settings, it does not load properly, instead showing a blank white window when I right click the icon and select "Open". No notifications are present, either.

I suspect that the problem is related to the fact that the Wi-Fi connection is not yet active when KDE autostarts the program. I tried starting it after manually disconnecting, and got the same result: a blank white window. Connecting afterwards does not fix the problem once ghetto-skype is already launched, and the window remains blank white. Unlike regular Skype for Linux, it seems ghetto-skype does not listen to network connection status changes and does not try to connect once the network is up. It should probably listen to network-manager events via D-Bus.

This or something similar could help: https://www.npmjs.com/package/nm-dbus

**Comment by stanfieldr** [comment]
I'll fix this when I get off work, thanks for the info about Network Manager :)

**Comment by SirTempest** [comment]
Any update on this?

**Comment by stanfieldr** [comment]
Sorry for the delay -- it's a bit more involved than I originally thought. Right now the client supports using a proxy, so I need to check whether Web Skype is accessible through the proxy as well. I have regular internet connections working, but was trying to get this all into one release. I'll release it by Friday, whether I have full proxy support or not by then.

**Comment by stanfieldr** [comment]
This should work now in [v1.2.3](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.2.3). It still has a white screen, but it'll reconnect when you have internet access again. I'm planning on revamping the this in 1.3 along with the tray icon and ability to set availability status.
