### ISSUE TITLE
32 Bit support

### ISSUE THREAD

**Issue by sergioad** [stanfieldr/ghetto-skype#23]
Hi friends could you soon add the possibility to compile this app for 32 bit operating systems? actually Skype for Linux's video and audio calls are not working because of how old are the last official Skype builds for Linux so could be amazing to be able to use Skype on our PC with this app

**Comment by stanfieldr** [comment]
Does the [v1.2.3](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.2.3) package work for you? Unfortunately Web Skype doesn't support video yet; however, audio should work as long as you initiate the call.

**Comment by sergioad** [comment]
@stanfieldr Sir I am in Arch and the AUR pkgbuild has not support for 32 bits yet, when I try to compile it trought yaourt it says me that there is not 32 bit support

**Comment by techwiz24** [comment]
@sergioad please open an issue against [techwiz24/aur-ghetto-skype](https://github.com/techwiz24/aur-ghetto-skype) for AUR issues and I'll take a look at this.

**Comment by stanfieldr** [comment]
Awesome, thanks @techwiz24 :)

**Comment by sergioad** [comment]
@techwiz24 thank you very much :smile:
