### ISSUE TITLE
drag and drop of file : text or image is display in stead upload to the conversation

### ISSUE THREAD

**Issue by maxdelorme** [stanfieldr/ghetto-skype#24]
when the image is display or the text, 
there is no way to go back to the default view

**Comment by stanfieldr** [comment]
This looks like a bug with electron, I opened an issue [upstream](https://github.com/electron/electron/issues/5853). I'll take a look at it.

**Comment by stanfieldr** [comment]
I pushed a fix to the develop branch if you want to test it. I'm going to do some more work this weekend, so will do a release on Monday.

**Comment by stanfieldr** [comment]
This is now in [v1.3.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.3.0)

**Comment by maxdelorme** [comment]
Thanks !

2016-06-07 2:59 GMT+02:00 Robert Stanfield <notifications@github.com>:

> This is now in v1.3.0
> <https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.3.0>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/stanfieldr/ghetto-skype/issues/24#issuecomment-224133143>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AK95T41N3xo74CDiJMvu2J5JucL9tyCxks5qJMJ3gaJpZM4Itd_k>
> .
>



-- 
-------------------------------------------------------------------------------------------------------
Maxime Delorme
Directeur du développement logiciel
4, rue du Faubourg Montmartre, 75009 Paris

Fixe :    +33 1 79 74 16 96
Mobile : +33 6 61 52 00 46
---------------------------------------------------------------------------------------------------------

-- 

<http://www.tennaxia.com?signature=logo>
____________________________

  <http://www.tennaxia.com/contact>  
<https://www.linkedin.com/company/tennaxia?signature=linkedin>   
<http://www.viadeo.com/fr/company/tennaxia?signature=viadeo>   
<https://twitter.com/Tennaxia?signature=twitter>   

*Adoptez l'éco-attitude. N'imprimez ce mail que si cela est vraiment 
nécessaire !*
