### ISSUE TITLE
Leaving ghetto-skype open after screen lock

### ISSUE THREAD

**Issue by lyndon160** [stanfieldr/ghetto-skype#28]
I lock my screen and leave ghetto-skype open for long periods of time. When I come back to it, it appears as if I'm still logged on - however, I cannot receive messages and sending messages doesnt work either.

Frustrating as you can easily not see messages for a long time. I've resorted to restarting it every time I login.

**Comment by stanfieldr** [comment]
Are you saying that it doesn't change the status on Skype to "away" or that the window becomes unusable when you unlock the screen? I definitely look into that first one. Let me know if the second issue is also a problem.

**Comment by lyndon160** [comment]
The second one is sort-of what I mean.

I don't know if it actually has anything to do with locking the screen but it might. It's when I leave my computer for a while (from an hour to overnight) then the window is still responsive but I cannot receive or send messages. As soon as I notice (normally when I get a skype message to my phone) I restart ghetto-skype and it works.

**Comment by dzek69** [comment]
It just disconnects after a while (especially when computer is set to sleep). The same may happen when using the browser with web skype. The fix is to refresh the page.

I guess you can detect it somehow, as text input gets read only or something after it happens.

**Comment by orange-buffalo** [comment]
I also experience this problem. After some time (most often after sleep, but occasionally in normal working mode) skype is disconnected and I do not receive messages and my messages are not delivered when I send them.

**Comment by 0v3rth3d4wn** [comment]
Same here. I went out for lunch and my screen locked. After I cam back, a lot of people were writing me, but I didn't receive anything. I had to restart it in order to fix it.

**Comment by BluPix** [comment]
Same problem. Maybe ghetto-skype need some form of watchdog, reload page if it it freezes.

**Comment by stanfieldr** [comment]
This has been happening to be constantly in the the mornings at work lately. Sorry I haven't got to this yet, I know how annoying it is! Going to take a look this weekend

**Comment by diego-XA** [comment]
This also happens in the web.skype.com, so the problem is on the skype side (how odd is that, right?). So far the only workaround I've found is to periodically reload the tab so maybe this workaround could be implemented inside ghetto-skype.

If possible, I think the best implementation would be to reload the page after 30 minutes of the last time it was "used" (typed, called, etc), or after 30 min of last reload.

**Comment by stanfieldr** [comment]
I tried to hash this out over the weekend and I couldn't reproduce the problem. I did manage to debug it at work but I'm still getting polling http requests to skype which was kinda weird to me. I'll go ahead and just set a 30 minute interval like you said. Probably check for user input first and if there was any activity in the last minute before refreshing.

**Comment by stanfieldr** [comment]
Included in [v1.4.1](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.1)
