### ISSUE TITLE
Package is of bad qaulity

### ISSUE THREAD

**Issue by lyndon160** [stanfieldr/ghetto-skype#29]
This pops up whilst installing/upgrading the package on Ubuntu.

**Comment by stanfieldr** [comment]
What version of Ubuntu are you running?

**Comment by stanfieldr** [comment]
nvm I see it now

**Comment by stanfieldr** [comment]
Fixed in [v1.3.2](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.3.2)
