### ISSUE TITLE
Always redirects to Microsoft login

### ISSUE THREAD

**Issue by rami999999999** [stanfieldr/ghetto-skype#3]
Hello,

I'm not sure way but it is always redirecting me to microsoft login. I guess the problem is in views/skype.js:heckMicrosoftAccount(currentURL)

I added the dumb condition:
 ```
if ('0'=== '0') {
        
       }
        
        else if (currentURL.hostname === "login.skype.com" && currentURL.query.client_id)
```

to force skipping microsoft login. I guess the original condition is not ok...

BTW the settings.json is ok:
```
cat settings.json 
{
	"StartMinimized": false,
	"MicrosoftAccount": false
}

```

**Comment by stanfieldr** [comment]
This should be fixed now :)
