### ISSUE TITLE
User with older version of Skype don't receive messages from Ghetto

### ISSUE THREAD

**Issue by dmkuznetsov** [stanfieldr/ghetto-skype#38]
Text messages doesn't work if your contacts use an older version of Skype.
I have tried to send few text messages to my friend with Skype for Linux. But he didn't receive anything

> Ghetto version v1.3.2
> lsb_release -a
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04 LTS
> Release:	16.04
> Codename:	xenial

**Comment by stanfieldr** [comment]
Tell your friend to type

> /msnp24

Then he has to restart skype and it should work.
