### ISSUE TITLE
Click tray and bring to front

### ISSUE THREAD

**Issue by MavropaliasG** [stanfieldr/ghetto-skype#39]
Thanks for your amazing app.

When I click the tray icon the client is minimized. Isn't it possible to bring it to front and to remember last window setting ?

Thanks once more

**Comment by stanfieldr** [comment]
What desktop environment do you use? Yea it should be possible, on some distros like Ubuntu the click event doesn't work, it opens the context menu instead.

**Comment by MavropaliasG** [comment]
@stanfieldr somehow now it works, and when I click it the tray it brings it to the front not just minimized in the taskbar. I am using Cinnamon 2.8.8 under Mint 17.3. Anyway feel free to close this thank so much for the client !

**Comment by stanfieldr** [comment]
I actually think I figured out what happened because it just happened to me. I think I fixed it, will include in next release.

**Comment by MavropaliasG** [comment]
Sometimes it happens, others it does not. I'm not sure if its my system.

Thanks man you are awesome.
