### ISSUE TITLE
Delete conversation window under dark theme not displaying text

### ISSUE THREAD

**Issue by MavropaliasG** [stanfieldr/ghetto-skype#40]
When using the dark theme, and I right click on a conversation and choose "delete conversation" the emergin window has no text, but it does if I am using the light text.

**Comment by stanfieldr** [comment]
Fixed, I'll let you know when I tag the new release

**Comment by stanfieldr** [comment]
Included in [v1.4.1](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.1)

**Comment by MavropaliasG** [comment]
You rock man, thanks !
