### ISSUE TITLE
"npm install" command fails

### ISSUE THREAD

**Issue by comtom** [stanfieldr/ghetto-skype#42]
this is the output:

comtom@andarta:~/tmp/ghetto-skype$ npm install
npm WARN engine grunt-electron-packager@0.0.7: wanted: {"node":"~5.5.0","npm":"~3.3.12"} (current: {"node":"4.4.7","npm":"1.4.21"})
npm WARN deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0 - read more at https://github.com/electron-userland/electron-packager/issues/333
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
 
> electron-prebuilt@1.2.6 postinstall /home/comtom/tmp/ghetto-skype/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@1.2.6 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.2.6 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/comtom/tmp/ghetto-skype
npm ERR! node -v v4.4.7
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/comtom/tmp/ghetto-skype/npm-debug.log
npm ERR! not ok code 0

**Comment by stanfieldr** [comment]
> sh: 1: node: not found

I think for Debian based distros you need to install this as well `sudo apt-get install node-legacy`

I fixed a dependency error too :)
