### ISSUE TITLE
Tray icon is displayed as colored rectangle under KDE Plasma 5

### ISSUE THREAD

**Issue by lucidfox** [stanfieldr/ghetto-skype#46]
Under Kubuntu 16.04, instead of the actual icon in the application data files (the letter S in a blue or red circle), I get two blue or red rectangles.
![ghetto-skype-icon-plasma](https://cloud.githubusercontent.com/assets/10684/16812067/a63704e2-4955-11e6-8219-e9f0e2304453.png)

**Comment by stanfieldr** [comment]
Odd, I'll take a look. Thanks for reporting

**Comment by tneo** [comment]
On my desktop with openSUSE Leap I have the same issue. On my laptop with Leap all is fine...

**Comment by anlar** [comment]
Looks like KDE don't want to resize tray icon (if you resize it yourself to 24x24 it will fit fine). It seems like common issue with electron apps on KDE: https://github.com/sindresorhus/caprine/issues/58

**Comment by stanfieldr** [comment]
Fixed in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0)
