### ISSUE TITLE
Add option to suppress notification pop-ups

### ISSUE THREAD

**Issue by tneo** [stanfieldr/ghetto-skype#51]
In the 4.3 client you don't see pop-ups when a message has arrived. Is it possible to add a setting to not show the system notification pop-up when message has arrived. A fine grained setting that allows to show pop-up in case of mention by @usernames would be nice.

**Comment by andey** [comment]
+1 - How do I disable the libnotify notifications completely?

**Comment by stanfieldr** [comment]
I can probably squeeze disabling notifications completely in the upcoming release, seems easy enough. It'll require a little bit more programming to sniff out the @username, so I will probably hold up on that till the next release.

**Comment by stanfieldr** [comment]
Added ability to turn off notifications in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0). I'll try to tackle the @username in the next one.

**Comment by tneo** [comment]
Great, going to try it out right away.
