### ISSUE TITLE
Clicking system tray icon opens ghetto in background

### ISSUE THREAD

**Issue by tneo** [stanfieldr/ghetto-skype#52]
When I click on the system tray icon, the ghetto client is not brought to the foreground. The window is opened in the background, forcing me to click again on the application window to bring the client to the foreground.

I'm running Plasma5 if that matters.

**Comment by stanfieldr** [comment]
This is actually fixed in the repo, it'll be included in the next release. I will try to have that out by Friday

**Comment by stanfieldr** [comment]
Fixed in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0)
