### ISSUE TITLE
Conversations not showing up even when favorited

### ISSUE THREAD

**Issue by zurbergram** [stanfieldr/ghetto-skype#53]
I'm using Linux Mint 18 Cinnamon and I favorited a conversation in Skype and that conversation doesn't show up in ghetto skype.  It wasn't showing before I favorited it either.  Is there a size limit to conversations?

**Comment by andey** [comment]
@zurbergram does it show up in web.skype.com ? I don't think this issue is within the scope of ghetto-skype

**Comment by zurbergram** [comment]
appears to be a skype issue not a ghetto skype issue

**Comment by zurbergram** [comment]
No, i send an support email to skype and close the issue
