### ISSUE TITLE
Ubuntu Gnome 16.04 - Launches second instance if you click shortcut while program is in tray

### ISSUE THREAD

**Issue by shihrer** [stanfieldr/ghetto-skype#54]
Hopefully the title makes sense.  At least on Ubuntu Gnome, if I minimize to tray and then click the shortcut on my dock it loads another instance of the program rather than open another.  I use about 3 Electron based applications that minimize to tray and this is the only one that does it, although they each behave slightly different.

Here's a screenshot of what I'm talking about:
![screenshot from 2016-07-14 10-15-32](https://cloud.githubusercontent.com/assets/9060431/16846993/077a08fc-49ac-11e6-99de-0bfe33cd7ced.png)

Figured I'd just let you know.  Normal behavior is to bring the app to the foreground.

**Comment by stanfieldr** [comment]
Fixed in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0)

**Comment by shihrer** [comment]
Great work, I'll check it out soon.
