### ISSUE TITLE
Dark Theme text is not readable in Blocking dialog

### ISSUE THREAD

**Issue by CODeRUS** [stanfieldr/ghetto-skype#55]
Hello,
When using dark theme if you want to block some user you can't read text inside window.
![1 skype_010](https://cloud.githubusercontent.com/assets/720601/16867650/c2f7a330-4a94-11e6-8fa3-ecece02fff54.png)
![1 skype_011](https://cloud.githubusercontent.com/assets/720601/16867653/c7121bd0-4a94-11e6-9ecb-cb24a22d47d9.png)

**Comment by stanfieldr** [comment]
Fixed in the repo, I'll release sometime tonight

**Comment by stanfieldr** [comment]
Fixed in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0)
