### ISSUE TITLE
Set the browser id to Chrome/ium so that we can have proper audio calls without plugin installation popups.

### ISSUE THREAD

**Issue by PrMinisterGR** [stanfieldr/ghetto-skype#56]
Since Microsoft released their Skype "client" (which is much worse than Ghetto-Skype, and it doesn't even let me login), they allow calls from Chrome/ium. Change the browser id of Ghetto-Skype and make it even better!

**Comment by stanfieldr** [comment]
Fixed in [v1.4.0](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.0)
