### ISSUE TITLE
Add the urgent window flag when you receive messages

### ISSUE THREAD

**Issue by WebFreak001** [stanfieldr/ghetto-skype#57]
Right now you can only see that you have new messages from the tray icon. Adding the urgency hint to the window would make it easier for people to see on multiple window managers

**Comment by stanfieldr** [comment]
Seems like [this](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winflashframeflag) will do the trick. I'll add it to the next release, thanks :)

**Comment by mdovgialo** [comment]
You can always use pulsaudio with pulsaudio-module-jack.

**Comment by stanfieldr** [comment]
Included in [v1.4.1](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.1)
