### ISSUE TITLE
Use electron.shell.openItem instead of xdg-open

### ISSUE THREAD

**Issue by CODeRUS** [stanfieldr/ghetto-skype#58]
Hi, i just tried to use ghetto-skype on windows, and it works excellent, except hardcoded xdg-open spawn. Replaced with electron.shell.openItem and attachments now opens fine :)

I believe same code works in linux too, so you can remove one more hardcoded stuff :)

**Comment by stanfieldr** [comment]
Nice, thanks for the tip. Added
