### ISSUE TITLE
Proxy option missing

### ISSUE THREAD

**Issue by konig1** [stanfieldr/ghetto-skype#6]
When connecting from an environment required to forward request through a proxy, the startup page stays white. Is the a possibility to define a proxy server through the config file?

**Comment by stanfieldr** [comment]
Yea I'll try to start tackling proxy support tomorrow. I have to do some more research on it, but it looks possible.

**Comment by stanfieldr** [comment]
Hey I added a way to set the proxy through the settings file, can you test it to make sure it's working properly? I tested a free http proxy using http://www.whereisip.net/ and it seems to be working.

**Comment by stanfieldr** [comment]
Fixed in release v1.1

**Comment by konig1** [comment]
Hey, I'll give it a try from behind a corporate proxy and report back.

Thanks
Dan

On Fri, May 13, 2016 at 4:10 AM, Robert Stanfield <notifications@github.com> wrote:

Closed #6<https://github.com/stanfieldr/ghetto-skype/issues/6>.
