### ISSUE TITLE
Some contacts that are offline appear online in Ghetto Skype

### ISSUE THREAD

**Issue by MavropaliasG** [stanfieldr/ghetto-skype#62]
I have both the official client of Skype and Ghetto Skype open side by side, and for some reason, some offline contacts appear online.

I have logged in to https://web.skype.com/ and the contact status there is correct. 

So it seems to be a bug of ghetto skype.

Does it have something to do with the cache the program uses ?

**Comment by stanfieldr** [comment]
Does this happen if you restart Ghetto Skype? This may be related to #28

**Comment by MavropaliasG** [comment]
No, It happens all the time even if I open or close it, restart the computer, I even tried "sudo apt-get purge ghetto-skype" and removed it completely and when reinstalling ANOTHER version ( I went from 1.3.4 to 1.4) it still persists. The problem only goes away when I open my other distro I installed in my pc and open ghetto-skype there, then its normal. Somehow ghetto-skype cached information that won't be removed with apt-get purge and they are bugged.

**Comment by stanfieldr** [comment]
weird okay... I think a temporary solution after installing 1.4 would be to rm -r ~/.config/Ghetto\ Skype although be aware this will wipe your settings out.

**Comment by MavropaliasG** [comment]
I'm not sure what happening, ghetto skype calling is not working for me at all anymore. I am not able to hear people and neither they can do. I will use official skype for now and will try again ghetto skype when I will upgrade my system in 2 weeks. I hope I wont come against the same problems there.
