### ISSUE TITLE
Add an option to disable graphical emoticons

### ISSUE THREAD

**Issue by JaneSmith** [stanfieldr/ghetto-skype#63]
Both the older 4.3 Linux client, and the current Windows client, have an option to display emoticons as plain text instead of graphical emoticons. I've always preferred plain text emoticons for two reasons:
1. I want to simply type my emoticons and see them as I've typed them, not have them randomly converted into graphics (sometimes breaking the typed emoticon entirely if it "detects" it in a way that I didn't intend).
2. The graphical emoticons in Ghetto Skype are HUGE. They take up a ton of space, wasting valuable screen space that could be used to display other text messages.

Would it be possible to get this feature added? A bonus would be an option to resize the emoticons, but just being able to disable them completely is more important.

I'm no expert, but I'm thinking you could do it by scanning for the emoticon images and then just replacing them with their text equivalents?

**Comment by meliezer** [comment]
This is also useful in working places.
The meaning of each emoticon and the related text abbrevation can be found upon hovering over the menu for selecting one (in web.skype.com).

Kind regards,
Menashè

**Comment by Pilzbauer** [comment]
Well, what a bummer, this is already supported by the Skype web view. Should be closed.
