### ISSUE TITLE
Zoom settings not working anymore

### ISSUE THREAD

**Issue by FiraWolf** [stanfieldr/ghetto-skype#72]
Ghetto Skype is ignoring my zoom settings since 2 or 3 updates. At first it was random and could be fixed with a restart but now the zoom level stays at 100% no matter what. I'm configuring via ~/.config/Ghetto Skype/settings.json

I'm using the dark theme if that matters.

I think Issue 71 (https://github.com/stanfieldr/ghetto-skype/issues/71) is related to this.

----

Not sure if needed:
Always recent Arch Linux, KDE, installed via AUR, NVidia proprietary blob

**Comment by stanfieldr** [comment]
Fixed in develop, will be in next release

**Comment by stanfieldr** [comment]
Included in [v1.4.1](https://github.com/stanfieldr/ghetto-skype/releases/tag/v1.4.1)
