### ISSUE TITLE
Coloring Ghetto Skype

### ISSUE THREAD

**Issue by ryancito02** [stanfieldr/ghetto-skype#74]
I looked at the README, and saw that the main contributer's Ghetto Skype was conveniently and exotically colored. I wonder how I can color my own G. S. to be that way.

Anyone know how?

**Comment by stanfieldr** [comment]
There's a settings option if you right click the try icon, change the theme to dark :)

**Comment by ryancito02** [comment]
I have no idea where the try (or tray) icon is.

Could you send a screenshot or direct me verbally to it?

**Comment by stanfieldr** [comment]
![20160805_221006](https://cloud.githubusercontent.com/assets/7494573/17454138/073cb51e-5b5a-11e6-864e-146c5aa6e164.jpg)

It is usually located in the top right or bottom right most of the time although Gnome has a somewhat hidden tray on the left of your screen if you hover over the right side of your screen. I'll go ahead and add a menu to the main window so it's a little easier to locate.
