### ISSUE TITLE
Grunt Error with Dev Version

### ISSUE THREAD

**Issue by ryancito02** [stanfieldr/ghetto-skype#78]
I have followed along and installed dependencies and made the package. Below is a list of the commands I have performed so far..

sudo make install            (doesn't work the first time, needed to install NPM and node and nodejs)

sudo npm -g grunt

sudo npm install

sudo grunt deb  ( fails. Error below )

/home/cortanium/Desktop/ghetto-skype-develop/Gruntfile.js:5
let arch = os.arch();
    ^^^^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected identifier
Warning: Task "deb" not found. Use --force to continue.

Aborted due to warnings.

I have installed LET through NPM and all neccesary packages. 
What is going wrong?

**Comment by stanfieldr** [comment]
I didn't realize this, but it seems older versions of node doesn't support some features Ghetto Skype uses. Try doing the following:

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
# Exit terminal and/or open new one
nvm install v6.3.1
nvm use v6.3.1
# Go to Ghetto Skype directory
npm install
# You'll need to install grunt for this version of node
npm install -g grunt
grunt deb
```

Then you can go back to your distro node once it's built
`nvm use system`

I'll update the readme sometime this weekend :)
