### ISSUE TITLE
change theme

### ISSUE THREAD

**Issue by bart00777** [stanfieldr/ghetto-skype#79]
I have the latest version and there is no option to change the theme, debian jessie

**Comment by Xiuhquiauitl** [comment]
Found it from looking at the code - you have to add a new setting `"Theme": "dark"` in `~/.config/Ghetto\ Skype/settings.json`.
Would likely make sense if the Theme-setting was in there by default.

**Comment by DrupaListo-com** [comment]
+1, please add note for this in the readme and also a "Theme": "normal" / "Theme": "light" in the default settings.json so people can see it there...

**Comment by DrupaListo-com** [comment]
PS. I just now found out that right clicking the tray icon gives a SEPARATE settings page/screen - different from the clog wheel in web-skype... So there is the settings page to change theme etc...
Ok - good if there was a NOTE for that in README too..

**Comment by stanfieldr** [comment]
I put a note in the readme, also added "Theme": "default" to setttings.json
