### ISSUE TITLE
ghetto-skype not working

### ISSUE THREAD

**Issue by Allieway** [stanfieldr/ghetto-skype#85]
It says Oops, something went wrong at our end
Sending one of our engineers to fix it. Give it a couple of minutes and try again. 

The issue is that it works fine on the browser and has been giving me this error with multiple restarts for the last day. Just checking to see if anyone else is having this issue or if anyone knows a fix?

**Comment by stanfieldr** [comment]
can you provide the contents of this file: `~/.config/Ghetto\ Skype/settings.json`?

**Comment by Allieway** [comment]
```
{
	"StartMinimized": false,
	"MicrosoftAccount": false,
	"NativeImageViewer": false,
	"Mute": false,
	"EnableNotifications": true,
	"OpenWhenMessaged": false,
	"ProxyRules": "",
	"ZoomFactor": 1,
	"RefreshInterval": 30,
	"mainWindow": {
		"width": 910,
		"height": 599
	}
}
```

**Comment by Allieway** [comment]
Let me know if you need any more info.

**Comment by stanfieldr** [comment]
I haven't had any luck reproducing this unfortunately

**Comment by Allieway** [comment]
This was fixed today. I believe I updated to a newer version over the weekend from AUR. Not sure if that fixed it or it was coincidence. Thanks for trying to reproduce it, appreciate it!
