### ISSUE TITLE
Improve send message by ctrl+Enter

### ISSUE THREAD

**Issue by chevi** [stanfieldr/ghetto-skype#87]
Is there any possibility to add setting for sending messages by Ctrl+Enter keys? Now Enter sends message and Shift+Enter makes new row. But needs: Enter - new row; Ctrl+Enter - send

**Comment by stanfieldr** [comment]
Yep, I can make a system preference for this :)

**Comment by stanfieldr** [comment]
Added, will be included in this upcoming version
