### ISSUE TITLE
Please provide an ability to change zoom level (or font size)

### ISSUE THREAD

**Issue by Mentis** [stanfieldr/ghetto-skype#9]
subj

**Comment by stanfieldr** [comment]
Hello and thanks for the suggestion. I added a quick fix so you can use the zoom feature now, I'll make it a little easier to adjust/set when I have some free time. For now you can use [this section](https://github.com/stanfieldr/ghetto-skype#setting-zoom-level) for guidance.

**Comment by Mentis** [comment]
Thank you. That's great!
