### ISSUE TITLE
"chromewebdata" instead of content

### ISSUE THREAD

**Issue by vi** [stanfieldr/ghetto-skype#90]
I open ghetto-skype and see white window with just plain text that reads "chromewebdata" instead of web.skype.com content. It does auto-restore or reload after a while. Only restarting ghetto-skype helps.

Settings window displays properly.

Can it be caused by intermittent network problems?

**Comment by vi** [comment]
Version is 1.4.1-1

**Comment by tiagorinaldi** [comment]
Same here. Just happened to me

**Comment by lcd1232** [comment]
The same problem. Log
`Failed to load: {"isTrusted":false,"errorCode":-137,"errorDescription":"ERR_NAME_RESOLUTION_FAILED","validatedURL":"https://web.skype.com/en","isMainFrame":true}
`

**Comment by stanfieldr** [comment]
Does this work in 1.5?

**Comment by bentasker** [comment]
I used to suffer from this quite badly in 1.4 on my laptop (presumably something to do with constantly losing connectivity for a while whilst I travelled). I've not seen it at all so far in 1.5

**Comment by stanfieldr** [comment]
Awesome! Let me know if you guys have any more issues with this and I'll reopen
