### ISSUE TITLE
How I can make it for Windows?

### ISSUE THREAD

**Issue by denisgolius** [stanfieldr/ghetto-skype#91]
How I can make Windows version of ghetto-skype with my own theme?
Or can yo write little instruction for this? =)
![2016-09-11 12-32-58](https://cloud.githubusercontent.com/assets/5650611/18416428/3df84cf0-781d-11e6-914d-1ca219be79fd.png)

**Comment by Kuchiriel** [comment]
@denisgolius https://github.com/electron/electron/blob/master/docs/development/build-instructions-windows.md
